OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: AdminOrg
    Domain: admin.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: ZoneInspectorOrg
    Domain: zoneinspector.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: OperationManagerOrg
    Domain: operationmanager.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: FieldInspectorOrg
    Domain: fieldinspector.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
